In [1]:
import requests

In [2]:
import bs4

In [10]:
url = "https://quotes.toscrape.com/page/{}/"

n = 1
flag = True
authors = []
while flag:

    print(n)
    print(url.format(n))
   
    code = requests.get(url.format(n))
    soup = bs4.BeautifulSoup(code.text, 'lxml')


    flag = soup.select(".quote") != []

    author = soup.select(".author")
    for auth in author
        authors.append(author.text)
    
    n = n + 1



SyntaxError: invalid syntax (<ipython-input-10-8cc41e96652b>, line 18)

In [1]:
import numpy as np

In [20]:
data = np.random.randn(2,3)

In [21]:
data

array([[-0.26686524, -0.37129292,  0.95519707],
       [ 0.39237294,  1.29859222,  0.8401395 ]])

In [23]:
data*data

array([[0.07121705, 0.13785843, 0.91240144],
       [0.15395653, 1.68634176, 0.70583439]])

In [26]:
np.sum(data, axis = 1)

array([0.31703892, 2.53110467])

In [1]:
import os

In [10]:
data = os.walk('Data-Sciences')

In [4]:
pwd

'C:\\Users\\harik\\Desktop\\Python'

In [11]:
for folder, subfolders , files in data:
    print(folder)
    for subfolder in subfolders:
        print(subfolder)
        
    for file in files:
        print(file)

Data-Sciences
.git
Notes
.gitattributes
Data-Sciences\.git
hooks
info
logs
objects
refs
COMMIT_EDITMSG
config
description
FETCH_HEAD
HEAD
index
packed-refs
Data-Sciences\.git\hooks
applypatch-msg.sample
commit-msg.sample
fsmonitor-watchman.sample
post-update.sample
pre-applypatch.sample
pre-commit.sample
pre-merge-commit.sample
pre-push.sample
pre-rebase.sample
pre-receive.sample
prepare-commit-msg.sample
update.sample
Data-Sciences\.git\info
exclude
Data-Sciences\.git\logs
refs
HEAD
Data-Sciences\.git\logs\refs
heads
remotes
Data-Sciences\.git\logs\refs\heads
main
Data-Sciences\.git\logs\refs\remotes
origin
Data-Sciences\.git\logs\refs\remotes\origin
HEAD
main
Data-Sciences\.git\objects
00
02
03
04
06
07
08
0a
0c
0f
10
12
13
14
18
1d
1f
20
21
22
23
24
25
28
29
2c
2d
2f
30
32
34
38
39
3e
3f
40
46
47
48
49
4a
4c
4e
50
51
52
53
55
56
57
58
59
5a
5b
5c
5f
62
64
65
66
67
68
69
6b
6d
6e
6f
70
71
72
73
74
75
76
77
79
7a
7b
7e
7f
80
82
83
84
86
89
8a
8b
8f
90
91
92
94
95
96
98
99
9a
9d
9e
a0


7b34a6c77e4cf6ec45eb690d8a751a45aa30ae
Data-Sciences\.git\objects\c3
87e6d5d531b7941bd4337449d0324e2dadaea7
Data-Sciences\.git\objects\c9
45d11acd3bd3e8a58ce3db3468789618d84fe8
Data-Sciences\.git\objects\ca
594f1a545ac30eac6abaa94bef314354f5c2dc
ef5a3ffff525aa3b90a4c3187698ddab18d1fe
Data-Sciences\.git\objects\cb
0dd70e3f817aafe2e8e60f3e74460b6800ca77
Data-Sciences\.git\objects\cc
9e9215d08d6cbc0a5a720bc1df54f6d66eb3e8
Data-Sciences\.git\objects\cf
d69e357f11e2142616190c955c1982a90ae92f
Data-Sciences\.git\objects\d2
0546b3ec628faf9c48fa516944b6c9af030fad
Data-Sciences\.git\objects\d4
e7de048e98c9b7dde3b1b451f34cfc612fa406
Data-Sciences\.git\objects\d5
752ef9d25c48b4be3f5957a246414077c32c91
Data-Sciences\.git\objects\d6
ec2e10f50c1090aae0f808c503df34e1a3e86a
Data-Sciences\.git\objects\d7
88af8042872ae643f4bd6bfa1d9bed9297832c
Data-Sciences\.git\objects\dc
8f37192b62b10815778a8b3b6e6fe812da0444
a4aa05953c5352308d1ea154cc741e7ead485f
Data-Sciences\.git\objects\dd
6baaa89664e54d0977c54c383

In [5]:
cd ..

C:\Users\harik\Desktop


In [7]:
os.listdir()

['Atom.lnk',
 'Books',
 'Data-Sciences',
 'desktop.ini',
 'GeoGebra Graphing Calculator.lnk',
 'GitHub Desktop.lnk',
 'Google Maps.lnk',
 'Groove Music.lnk',
 'JavaScript',
 'JioTV.lnk',
 'MEGAsync.lnk',
 'psiphon3.exe',
 'psiphon3.exe.orig',
 'Python',
 'R',
 'RStudio.lnk',
 'Star Chart.lnk',
 'System Volume Information',
 'TeraCopy.lnk',
 'WhatsApp.lnk',
 'Zoom.lnk',
 '\xa0']