In [19]:
import numpy as np
import scipy.linalg as la
import sympy as sp
import pandas as pd

In [4]:
la.eigvals(np.array([[1, 2], [3, 4]]))

array([-0.37228132+0.j,  5.37228132+0.j])

In [9]:
eigenval, eigenvec =  la.eig(np.array([[1, -1, 0], [-1, 1, 0], [0, 0, -1]]))

In [10]:
eigenvec

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [11]:
eigenval

array([ 2.+0.j,  0.+0.j, -1.+0.j])